-- Migrate class quest from monthly to weekly rotating cycle.
-- Exercise rotation anchored at 2026-06-01 (Monday), cycling every 5 weeks:
--   0 = Kniebeugen    (squats)
--   1 = Hampelmänner  (jumping_jacks)
--   2 = Liegestütze   (push_ups)
--   3 = Planks        (planks)
--   4 = Situps        (sit_ups)

-- ── 0. Drop old functions so parameter names can be changed ──────────────────
-- PostgreSQL does not allow renaming parameters via CREATE OR REPLACE.

DROP FUNCTION IF EXISTS public.get_class_quest_progress(date);
DROP FUNCTION IF EXISTS public.award_class_quest_bonus_if_complete(date);
DROP FUNCTION IF EXISTS public.get_class_rankings_with_quest_bonus(date);
DROP FUNCTION IF EXISTS public.get_code_class_quest_progress(text, text, date);

-- ── 1. Add week_start column to bonus-awards table ────────────────────────────

ALTER TABLE public.class_quest_bonus_awards
  ADD COLUMN IF NOT EXISTS week_start date;

-- Remove old month-based unique constraint (name generated by Postgres).
ALTER TABLE public.class_quest_bonus_awards
  DROP CONSTRAINT IF EXISTS class_quest_bonus_awards_school_class_month_start_key;

-- Partial unique index so ON CONFLICT works for new week-based rows.
DROP INDEX IF EXISTS public.idx_class_quest_bonus_awards_week;
CREATE UNIQUE INDEX idx_class_quest_bonus_awards_week
  ON public.class_quest_bonus_awards (school, class, week_start)
  WHERE week_start IS NOT NULL;

DROP INDEX IF EXISTS public.idx_class_quest_bonus_awards_month_class;
CREATE INDEX IF NOT EXISTS idx_class_quest_bonus_awards_week_class
  ON public.class_quest_bonus_awards (week_start, school, class);

-- ── 2. Helper: exercise index for a given week start (returns 0–4) ────────────

CREATE OR REPLACE FUNCTION public.get_quest_exercise_index(p_week_start date)
RETURNS integer
LANGUAGE sql
IMMUTABLE STRICT
AS $$
  SELECT (((p_week_start - DATE '2026-06-01') / 7 % 5) + 5) % 5;
$$;

-- ── 3. get_class_quest_progress (weekly, dynamic exercise column) ─────────────

CREATE OR REPLACE FUNCTION public.get_class_quest_progress(
  p_week_start date DEFAULT date_trunc('week', timezone('Europe/Vienna', now()))::date
)
RETURNS TABLE (
  student_id    uuid,
  username      text,
  contribution  integer,
  class_name    text,
  school_name   text,
  class_total   integer,
  goal          integer,
  rank_position integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_class  text;
  v_school text;
  v_goal   integer := 1000;
  v_wstart date := date_trunc(
    'week',
    COALESCE(p_week_start, timezone('Europe/Vienna', now())::date)::timestamp
  )::date;
  v_wend   date := v_wstart + 7;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT p.class, p.school INTO v_class, v_school
  FROM public.profiles p WHERE p.id = auth.uid();

  IF v_class IS NULL OR v_school IS NULL THEN RETURN; END IF;

  RETURN QUERY
  WITH students AS (
    SELECT p.id AS sid, p.username AS uname
    FROM public.profiles p
    WHERE p.class = v_class AND p.school = v_school
  ),
  contributions AS (
    SELECT
      s.sid,
      s.uname,
      COALESCE(SUM(
        CASE public.get_quest_exercise_index(v_wstart)
          WHEN 0 THEN COALESCE(dr.squats, 0)
          WHEN 1 THEN COALESCE(dr.jumping_jacks, 0)
          WHEN 2 THEN COALESCE(dr.push_ups, 0)
          WHEN 3 THEN COALESCE(dr.planks, 0)
          WHEN 4 THEN COALESCE(dr.sit_ups, 0)
          ELSE 0
        END
      ), 0)::integer AS amount
    FROM students s
    LEFT JOIN public.daily_results dr
      ON dr.user_id = s.sid
     AND dr.date >= v_wstart
     AND dr.date <  v_wend
    GROUP BY s.sid, s.uname
  ),
  totals AS (
    SELECT COALESCE(SUM(c.amount), 0)::integer AS total_amount FROM contributions c
  ),
  ranked AS (
    SELECT
      c.sid, c.uname, c.amount,
      row_number() OVER (ORDER BY c.amount DESC, c.uname ASC)::integer AS place
    FROM contributions c
  )
  SELECT r.sid, r.uname, r.amount, v_class, v_school, t.total_amount, v_goal, r.place
  FROM ranked r CROSS JOIN totals t
  ORDER BY r.amount DESC, r.uname ASC;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_class_quest_progress(date) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.get_class_quest_progress(date) TO authenticated;

-- ── 4. award_class_quest_bonus_if_complete (weekly) ──────────────────────────

CREATE OR REPLACE FUNCTION public.award_class_quest_bonus_if_complete(
  p_week_start date DEFAULT date_trunc('week', timezone('Europe/Vienna', now()))::date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id        uuid := auth.uid();
  v_class          text;
  v_school         text;
  v_goal           integer := 1000;
  v_reward         integer := 200;
  v_total          integer := 0;
  v_wstart         date := date_trunc(
    'week',
    COALESCE(p_week_start, timezone('Europe/Vienna', now())::date)::timestamp
  )::date;
  v_wend           date := v_wstart + 7;
  v_inserted_count integer := 0;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT p.class, p.school INTO v_class, v_school
  FROM public.profiles p WHERE p.id = v_user_id;

  IF v_class IS NULL OR v_school IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Keine Klasse gefunden');
  END IF;

  SELECT COALESCE(SUM(
    CASE public.get_quest_exercise_index(v_wstart)
      WHEN 0 THEN COALESCE(dr.squats, 0)
      WHEN 1 THEN COALESCE(dr.jumping_jacks, 0)
      WHEN 2 THEN COALESCE(dr.push_ups, 0)
      WHEN 3 THEN COALESCE(dr.planks, 0)
      WHEN 4 THEN COALESCE(dr.sit_ups, 0)
      ELSE 0
    END
  ), 0)::integer
  INTO v_total
  FROM public.profiles p
  LEFT JOIN public.daily_results dr
    ON dr.user_id = p.id
   AND dr.date >= v_wstart
   AND dr.date <  v_wend
  WHERE p.class = v_class AND p.school = v_school;

  IF v_total < v_goal THEN
    RETURN jsonb_build_object(
      'ok', true, 'awarded', false, 'already_awarded', false,
      'class_total', v_total, 'goal', v_goal, 'reward_points', v_reward
    );
  END IF;

  INSERT INTO public.class_quest_bonus_awards
    (school, class, week_start, goal, achieved_amount, reward_points)
  VALUES
    (v_school, v_class, v_wstart, v_goal, v_total, v_reward)
  ON CONFLICT (school, class, week_start) WHERE week_start IS NOT NULL DO NOTHING;

  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'ok', true,
    'awarded', v_inserted_count > 0,
    'already_awarded', v_inserted_count = 0,
    'class_total', v_total, 'goal', v_goal, 'reward_points', v_reward
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.award_class_quest_bonus_if_complete(date) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.award_class_quest_bonus_if_complete(date) TO authenticated;

-- ── 5. get_class_rankings_with_quest_bonus (weekly) ──────────────────────────

CREATE OR REPLACE FUNCTION public.get_class_rankings_with_quest_bonus(
  p_week_start date DEFAULT date_trunc('week', timezone('Europe/Vienna', now()))::date
)
RETURNS TABLE (
  school            text,
  class             text,
  total_flashes     integer,
  student_count     integer,
  sort_order        integer,
  quest_bonus_points integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH week_value AS (
    SELECT date_trunc(
      'week',
      COALESCE(p_week_start, timezone('Europe/Vienna', now())::date)::timestamp
    )::date AS wstart
  ),
  profile_counts AS (
    SELECT p.school, p.class, COUNT(*)::integer AS profile_student_count
    FROM public.profiles p
    WHERE p.school IS NOT NULL AND p.class IS NOT NULL
    GROUP BY p.school, p.class
  ),
  weekly_class_totals AS (
    SELECT
      p.school,
      p.class,
      COALESCE(SUM(
        CASE public.get_quest_exercise_index(wv.wstart)
          WHEN 0 THEN COALESCE(dr.squats, 0)
          WHEN 1 THEN COALESCE(dr.jumping_jacks, 0)
          WHEN 2 THEN COALESCE(dr.push_ups, 0)
          WHEN 3 THEN COALESCE(dr.planks, 0)
          WHEN 4 THEN COALESCE(dr.sit_ups, 0)
          ELSE 0
        END
      ), 0)::integer AS weekly_amount
    FROM public.profiles p
    CROSS JOIN week_value wv
    LEFT JOIN public.daily_results dr
      ON dr.user_id = p.id
     AND dr.date >= wv.wstart
     AND dr.date <  (wv.wstart + 7)
    WHERE p.school IS NOT NULL AND p.class IS NOT NULL
    GROUP BY p.school, p.class
  ),
  bonus_candidates AS (
    SELECT b.school, b.class, b.reward_points
    FROM public.class_quest_bonus_awards b
    CROSS JOIN week_value wv
    WHERE b.week_start = wv.wstart
    UNION ALL
    SELECT w.school, w.class, 200 AS reward_points
    FROM weekly_class_totals w
    WHERE w.weekly_amount >= 1000
  ),
  bonus AS (
    SELECT bc.school, bc.class, COALESCE(MAX(bc.reward_points), 0)::integer AS bonus_points
    FROM bonus_candidates bc
    GROUP BY bc.school, bc.class
  ),
  classes AS (
    SELECT r.school, r.class, r.total_flashes, r.student_count, r.sort_order, true AS is_active
    FROM public.presentation_class_rankings r
    UNION
    SELECT
      b.school, b.class,
      0 AS total_flashes,
      COALESCE(pc.profile_student_count, 0) AS student_count,
      9999 AS sort_order,
      true AS is_active
    FROM bonus b
    LEFT JOIN profile_counts pc ON pc.school = b.school AND pc.class = b.class
  )
  SELECT
    c.school,
    c.class,
    (COALESCE(MAX(c.total_flashes), 0) + COALESCE(MAX(b.bonus_points), 0))::integer AS total_flashes,
    GREATEST(COALESCE(MAX(c.student_count), 0), COALESCE(MAX(pc.profile_student_count), 0), 1)::integer AS student_count,
    MIN(c.sort_order)::integer AS sort_order,
    COALESCE(MAX(b.bonus_points), 0)::integer AS quest_bonus_points
  FROM classes c
  LEFT JOIN bonus b        ON b.school  = c.school  AND b.class  = c.class
  LEFT JOIN profile_counts pc ON pc.school = c.school AND pc.class = c.class
  WHERE c.is_active = true
  GROUP BY c.school, c.class
  ORDER BY total_flashes DESC, sort_order ASC, c.class ASC;
$$;

REVOKE EXECUTE ON FUNCTION public.get_class_rankings_with_quest_bonus(date) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.get_class_rankings_with_quest_bonus(date) TO authenticated;

-- ── 6. get_code_class_quest_progress (weekly, dynamic exercise column) ────────

CREATE OR REPLACE FUNCTION public.get_code_class_quest_progress(
  p_device_id     text,
  p_session_token text,
  p_week_start    date DEFAULT date_trunc('week', timezone('Europe/Vienna', now()))::date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session  public.active_sessions%ROWTYPE;
  v_student  public.students%ROWTYPE;
  v_class    public.classes%ROWTYPE;
  v_school   public.schools%ROWTYPE;
  v_wstart   date;
  v_wend     date;
  v_goal     integer := 1000;
  v_total    integer := 0;
  v_rows     jsonb;
BEGIN
  SELECT * INTO v_session
  FROM   public.active_sessions
  WHERE  device_id          = trim(p_device_id)
    AND  session_token_hash = encode(extensions.digest(p_session_token, 'sha256'), 'hex')
    AND  active             = true
    AND  user_type          = 'student'
    AND  COALESCE(expires_at, now() + interval '1 day') > now()
  ORDER BY created_at DESC LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Keine aktive Schueler-Session');
  END IF;

  SELECT * INTO v_student FROM public.students
  WHERE id = v_session.user_id AND active = true AND deactivated_at IS NULL;
  IF NOT FOUND THEN RETURN jsonb_build_object('error', 'Schueler nicht aktiv'); END IF;

  SELECT * INTO v_class  FROM public.classes  WHERE id = v_student.class_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error', 'Klasse nicht gefunden'); END IF;

  SELECT * INTO v_school FROM public.schools WHERE id = v_class.school_id;

  v_wstart := date_trunc(
    'week',
    COALESCE(p_week_start, timezone('Europe/Vienna', now())::date)::timestamp
  )::date;
  v_wend := v_wstart + 7;

  SELECT COALESCE(SUM(
    CASE public.get_quest_exercise_index(v_wstart)
      WHEN 0 THEN COALESCE(dr.squats, 0)
      WHEN 1 THEN COALESCE(dr.jumping_jacks, 0)
      WHEN 2 THEN COALESCE(dr.push_ups, 0)
      WHEN 3 THEN COALESCE(dr.planks, 0)
      WHEN 4 THEN COALESCE(dr.sit_ups, 0)
      ELSE 0
    END
  ), 0)::integer
  INTO v_total
  FROM   public.students s
  LEFT JOIN public.daily_results dr
         ON dr.user_id = s.id
        AND dr.date   >= v_wstart
        AND dr.date    < v_wend
  WHERE  s.class_id      = v_class.id
    AND  s.deactivated_at IS NULL;

  WITH per_student AS (
    SELECT
      s.id                                                         AS sid,
      s.display_name                                               AS uname,
      COALESCE(SUM(
        CASE public.get_quest_exercise_index(v_wstart)
          WHEN 0 THEN COALESCE(dr.squats, 0)
          WHEN 1 THEN COALESCE(dr.jumping_jacks, 0)
          WHEN 2 THEN COALESCE(dr.push_ups, 0)
          WHEN 3 THEN COALESCE(dr.planks, 0)
          WHEN 4 THEN COALESCE(dr.sit_ups, 0)
          ELSE 0
        END
      ), 0)::integer AS contribution
    FROM   public.students s
    LEFT JOIN public.daily_results dr
           ON dr.user_id = s.id
          AND dr.date   >= v_wstart
          AND dr.date    < v_wend
    WHERE  s.class_id      = v_class.id
      AND  s.deactivated_at IS NULL
    GROUP BY s.id, s.display_name
  ),
  ranked AS (
    SELECT sid, uname, contribution,
           row_number() OVER (ORDER BY contribution DESC, uname ASC)::integer AS rnk
    FROM per_student
  )
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'student_id',    sid,
      'username',      uname,
      'contribution',  contribution,
      'class_name',    v_class.name,
      'school_name',   v_school.name,
      'class_total',   v_total,
      'goal',          v_goal,
      'rank_position', rnk
    )
    ORDER BY rnk
  ), '[]'::jsonb)
  INTO v_rows
  FROM ranked;

  RETURN jsonb_build_object(
    'class_total', v_total,
    'goal',        v_goal,
    'class_name',  v_class.name,
    'school_name', v_school.name,
    'rows',        v_rows
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_code_class_quest_progress(text, text, date) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.get_code_class_quest_progress(text, text, date) TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
